version: '3.8'

services:
  sgg:
    image: gradle:8.7-jdk21
    working_dir: /app
    volumes:
      - ../services/sgg:/app
    command: ./gradlew bootRun
    ports:
      - "8080:8080"
  tournaments:
    image: gradle:8.7-jdk21
    working_dir: /app
    volumes:
      - ../services/tournaments:/app
    command: ./gradlew bootRun
    env_file:
      - .env.tournaments
    ports:
      - "8081:8080"